CREATE TABLE Cat (id INT AUTO_INCREMENT, Name VARCHAR(20), BirthDay DATE, Commands TEXT, PRIMARY KEY(id));
CREATE TABLE Dog (id INT AUTO_INCREMENT, Name VARCHAR(20), BirthDay DATE, Commands TEXT, PRIMARY KEY(id));
CREATE TABLE Hamster (id INT AUTO_INCREMENT, Name VARCHAR(20), BirthDay DATE, Commands TEXT, PRIMARY KEY(id));
CREATE TABLE Horse (id INT AUTO_INCREMENT, Name VARCHAR(20), BirthDay DATE, Commands TEXT, PRIMARY KEY(id));
CREATE TABLE Camel (id INT AUTO_INCREMENT, Name VARCHAR(20), BirthDay DATE, Commands TEXT, PRIMARY KEY(id));
CREATE TABLE Donkey (id INT AUTO_INCREMENT, Name VARCHAR(20), BirthDay DATE, Commands TEXT, PRIMARY KEY(id));

