CREATE TABLE cmd_info (
id INT AUTO_INCREMENT,
denotation VARCHAR(32),
PRIMARY KEY (id)
);

CREATE TABLE anm_data (
id INT AUTO_INCREMENT,
nick VARCHAR(32),
birth_day DATE,
comments VARCHAR(255),
PRIMARY KEY(id)
);

CREATE TABLE anm_type (
id INT AUTO_INCREMENT,
denotation VARCHAR(32),
PRIMARY KEY (id)
);

CREATE TABLE animals (
id INT AUTO_INCREMENT,
type_id INT,
data_id INT,
FOREIGN KEY (type_id) REFERENCES anm_type(id) ON DELETE CASCADE,
FOREIGN KEY (data_id) REFERENCES anm_data(id) ON DELETE CASCADE,
PRIMARY KEY (id) 
);

CREATE TABLE cmd_list (
id INT AUTO_INCREMENT,
anm_id INT NOT NULL,
cmd_id INT NOT NULL,
FOREIGN KEY (anm_id) REFERENCES animals(id) ON DELETE CASCADE,
FOREIGN KEY (cmd_id) REFERENCES cmd_info(id) ON DELETE CASCADE,
PRIMARY KEY (id)
);
