DROP DATABASE IF EXISTS anim_db;

CREATE DATABASE anim_db;
USE anim_db;

CREATE TABLE animals (
id INT AUTO_INCREMENT,
nick VARCHAR(32),
birth_day DATE,
comments VARCHAR(255),
PRIMARY KEY(id)
);

CREATE TABLE commands (
id INT AUTO_INCREMENT,
denotation VARCHAR(32),
PRIMARY KEY (id)
);

CREATE TABLE types (
id INT AUTO_INCREMENT,
denotation VARCHAR(32),
PRIMARY KEY (id)
);

CREATE TABLE sex (
id INT AUTO_INCREMENT,
denotation VARCHAR(8),
PRIMARY KEY (id)
);

CREATE TABLE cmd_list (
id INT AUTO_INCREMENT,
anm_id INT NOT NULL,
cmd_id INT NOT NULL,
FOREIGN KEY (anm_id) REFERENCES animals(id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (cmd_id) REFERENCES commands(id) ON UPDATE CASCADE ON DELETE CASCADE,
PRIMARY KEY (id)
);

CREATE TABLE typ_list (
id INT AUTO_INCREMENT,
anm_id INT NOT NULL,
typ_id INT NOT NULL,
FOREIGN KEY (anm_id) REFERENCES animals(id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (typ_id) REFERENCES types(id) ON UPDATE CASCADE ON DELETE CASCADE,
PRIMARY KEY (id)
);

CREATE TABLE sex_list (
id INT AUTO_INCREMENT,
anm_id INT NOT NULL,
sex_id INT NOT NULL,
FOREIGN KEY (anm_id) REFERENCES animals(id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (sex_id) REFERENCES sex(id) ON UPDATE CASCADE ON DELETE CASCADE,
PRIMARY KEY (id)
);
